package org.generateEntities;
// Generated Jan 25, 2018 11:58:01 AM by Hibernate Tools 5.2.8.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "CAR", schema = "dbo", catalog = "DBTest")
public class Car implements java.io.Serializable {

	private String id;
	private Serializable make;
	private Serializable model;

	public Car() {
	}

	public Car(Serializable make, Serializable model) {
		this.make = make;
		this.model = model;
	}

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "MAKE", nullable = false)
	public Serializable getMake() {
		return this.make;
	}

	public void setMake(Serializable make) {
		this.make = make;
	}

	@Column(name = "MODEL", nullable = false)
	public Serializable getModel() {
		return this.model;
	}

	public void setModel(Serializable model) {
		this.model = model;
	}

}
