package com.generatedEntities;
// Generated Jan 29, 2018 10:39:55 PM by Hibernate Tools 5.1.6.Final


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name="CAR"
    ,schema="dbo"
    ,catalog="DBTest"
)
public class Car  implements java.io.Serializable {


     private String id;
     private String make;
     private String model;

    public Car() {
    }

    public Car(String make, String model) {
       this.make = make;
       this.model = model;
    }
   
     @GenericGenerator(name="generator", strategy="guid")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="MAKE", nullable=false)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="MODEL", nullable=false)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }




}


